### ISSUE TITLE
OSGiELResolver can't resolve methods with parameters

### ISSUE THREAD

**Issue by adamjoeldavis** [camunda/camunda-bpm-platform-osgi#20]
There is an issue in the OSGiELResolver where it will only resolve methods that have zero parameters.  I don't think this is a bug in the OSGi extension, rather a bug in the way that the org.camunda.bpm.engine.impl.juel.AstMethod class passes parameter types down - it currently always passes null.

As a workaround, I have sub-classed the OSGiELResolver and modified the invoke() method like so:

```java
@Override
public Object invoke(ELContext context, Object base, Object method, Class<?>[] paramTypes, Object[] params)
{
    // need to build the param types, because they are null coming in here
    if((paramTypes == null || paramTypes.length == 0) && params != null && params.length > 0)
    {
        paramTypes = new Class<?>[params.length];
        for(int i = 0; i < params.length; i++)
        {
            paramTypes[i] = params[i] == null ? null : params[i].getClass();
        }
    }
        
    return super.invoke(context, base, method, paramTypes, params);
}
```

**Comment by rbraeunlich** [comment]
Hi Adam,
I created a [JUnit test](https://github.com/camunda/camunda-bpm-platform-osgi/blob/master/camunda-bpm-osgi/src/test/java/org/camunda/bpm/extension/osgi/el/OSGiELResolverLdapMethodCallWithParamIntegrationTest.java) to make this problem visibile and opened a [thread](https://groups.google.com/forum/#!topic/camunda-bpm-dev/Ky0hDJw6xRI) in the forum.
Depending on what we agree on there we'll change the OSGiELResolver or someone has to change the AstMethod class.
Cheers,
Ronny

**Comment by adamjoeldavis** [comment]
Hi Ronny,

Thanks for looking into this!  

Something else that I noticed:  The OSGiELResolver.invoke method uses MethodUtils.getAccessibleMethod, which forces an exact match on the Class<>[] defining the parameter types.  Would you consider switching to MethodUtils.getMatchingAccessibleMethod, which allows for non-exact, but still compatible, method parameters?

Thanks again!
Adam
