### ISSUE TITLE
I can download a prepackaged Apache Karaf distribution

### ISSUE THREAD

**Issue by meyerdan** [camunda/camunda-bpm-platform-osgi#21]
It should be possible for users to download an apache karaf distribution with camunda pre-installed (comparable to the tomcat, wildfly ... distributions we offer).

The distribution will be a community extension (no commercial support available).

camunda will add a link to http://camunda.org/download

The binaries can be downloaded directly from Github (?).

**Comment by wiax** [comment]
I agree with this idea; should be available as a feature embedded in a karaf distribution.

**Comment by rbraeunlich** [comment]
With the 1.1.0 release we provided the [Karaf distribution](https://github.com/camunda/camunda-bpm-platform-osgi/releases).
