### ISSUE TITLE
I can see which versions of camunda an OSGi release is compatible with

### ISSUE THREAD

**Issue by meyerdan** [camunda/camunda-bpm-platform-osgi#25]
Either on the [releases page](https://github.com/camunda/camunda-bpm-platform-osgi/releases) or somewhere else, I can see which versions of the process engine a particular OSGi extension release is compatible with.

**Comment by rbraeunlich** [comment]
Hi Daniel,
you're right, that would be some useful information.
I updated the release notes for 1.1.0. Unfortunately, I cannot add any description to 1.0.0. Seems like 1.0.0 wasn't a "usual" GitHub release. Maybe Christian can help me there?

**Comment by hawky-4s-** [comment]
Hi Ronny,

Just add some release notes through the [GitHub tags] url.

[GitHub tags]: https://github.com/camunda/camunda-bpm-platform-osgi/tags

**Comment by meyerdan** [comment]
https://github.com/camunda/camunda-bpm-platform-osgi/releases/new?tag=1.0.0

**Comment by rbraeunlich** [comment]
Thank you!
