### ISSUE TITLE
Adjust version range so that the OSGi extension works with Camunda BPM 7.3

### ISSUE THREAD

**Issue by mburke84** [camunda/camunda-bpm-platform-osgi#30]
Currently Camunda OSGi doesn't work with 7.3. This is because of the way that the version range is set. Can this be fixed?

**Comment by rbraeunlich** [comment]
2.0.0-SNAPSHOT and 1.1.0 both work with 7.3.0-SNAPSHOT.
So releasing a 1.2.0 shouldn't be a problem. Maybe we'll have to change some versions in the tests and feature.xml to fit to camunda platform.
