### ISSUE TITLE
Update readme link

### ISSUE THREAD

**Issue by MrWong99** [camunda/camunda-bpm-platform-osgi#31]
The [link](https://github.com/camunda/camunda-bpm-platform-osgi/blame/master/README.md#L26) in the main README (Line: 26) should point to 
https://github.com/camunda/camunda-bpm-platform-osgi/blob/master/camunda-bpm-karaf-feature/README.md
instead. You'll get a 404 with current link.

**Comment by meyerdan** [comment]
Thanks for reporting. The maintianer @rbraeunlich  will take care of this.
