### ISSUE TITLE
Update to Camunda Engine 7.4.0

### ISSUE THREAD

**Issue by funfried** [camunda/camunda-bpm-platform-osgi#32]
Hi, it would be awesome if you could update the Camunda OSGi integration to Camunda 7.4.0.

Kind regards

**Comment by rbraeunlich** [comment]
Hi @funfried,
I have exams next week but after those I should have enough time to take a look into it ;)
Cheers,
Ronny

**Comment by funfried** [comment]
That sounds awesome, but just to let you know, there's currently an open issue within Camunda 7.4.0:

https://app.camunda.com/jira/browse/CAM-5094

I don't think that it is currently possible to get Camunda 7.4.0 running in an OSGi container, but maybe you have an idea how to solve it or you find a workaround. But first take your time for your exams and ... viel Erfolg dabei ;)


Kind regards
funfried

**Comment by rbraeunlich** [comment]
Hi @funfried, just to let you know, I didn't forget you ;)
Unfortunately, to be able to create a version that works with 7.4 I had to fix [CAM-5094](https://app.camunda.com/jira/browse/CAM-5094).
Anyways, I'm making progess. But I can tell you now, that you'll have to compile your own 7.4 version to include the two pull requests ([#1](https://github.com/camunda/camunda-engine-dmn/pull/4), [#2](https://github.com/camunda/camunda-bpm-platform/pull/199)) that fix the MANIFESTS.
At least if you're using the community edition.

**Comment by funfried** [comment]
Hi @rbraeunlich,

sounds great, thanks for the update! And yes, we use the community edition and I'll give it a try as soon as possible.

**Comment by webtrekk-kane** [comment]
I currently have 7.4.0 community edition running inside Karaf. However, without camunda-spin and -connector so far.

If wanted, I can provide a patch for the engine.

**Comment by rbraeunlich** [comment]
Hello @funfried,
I am basically done with preparing the release. I had to open another [pull request](https://github.com/camunda/camunda-engine-dmn/pull/5) for camunda-engine-dmn but that should be it. You can try the 1.3 branch if you want to or wait until the release is published.
Cheers,
Ronny

**Comment by funfried** [comment]
Perfect, thanks, I'll give it a try.

**Comment by j0xaf** [comment]
Hello @rbraeunlich,

thanks for all your work on the Camunda OSGi integration :-).

One question regarding this issue: Camunda merged you PRs only in master (7.5.0). Do you expect they´ll backport those PRs also to 7.4.x or can we expect that OSGi (with officially built Camunda packages) will only be possible with 7.5.x?

Thanks & cheers
Jörn

**Comment by rbraeunlich** [comment]
Hi @j0xaf,

thank you for the praise ;)

@gimbel actually answered this question in [this pull request](https://github.com/camunda/camunda-bpm-platform/pull/200). Unless you're an enterprise customer you'll have to wait for the 7.5.0 release or build the 7.4 yourself. IF you're an enterprise customer I suppose you can apply "mild pressure" that camunda backports the changes.

Cheers,
Ronny

**Comment by rbraeunlich** [comment]
camunda 1.3.0 has been released
https://github.com/camunda/camunda-bpm-platform-osgi/releases/tag/1.3.0
