### ISSUE TITLE
Release camunda BPM 2.0.0

### ISSUE THREAD

**Issue by rbraeunlich** [camunda/camunda-bpm-platform-osgi#37]
I don't know if we have a CI running, but basically we can release the new version, which is compatible to camunda BPM 7.5.0

**Comment by rbraeunlich** [comment]
Did you make any progress here?

**Comment by meyerdan** [comment]
Hi Ronny, am sorry that we have not released it yet. I hope that Christian gets around to it next week.

**Comment by hawky-4s-** [comment]
Done.

**Comment by meyerdan** [comment]
Will it also be available on Maven Central?

**Comment by hawky-4s-** [comment]
Problem with release build, false positive

**Comment by hawky-4s-** [comment]
Alright, fixed the problem. See [release](https://github.com/camunda/camunda-bpm-platform-osgi/releases/tag/2.0.0). Also released on [maven central](https://oss.sonatype.org/content/repositories/releases/org/camunda/bpm/extension/osgi/).

**Comment by rbraeunlich** [comment]
Thank you very much for your help!
