### ISSUE TITLE
Evaluating a DMN-File in an OSGI-context possible?

### ISSUE THREAD

**Issue by avan2s** [camunda/camunda-bpm-platform-osgi#41]
Hello,
i have created a simple DMN-File and would like to evaluate it in an OSGI-context. Is it possible do use the decisions engine with DMN correctly in the OSGI-bundle? I am getting the error:  DMN-01002 Unable to evaluate expression for language 'juel': '${gender}'

 [Here](https://forum.camunda.org/t/evaluation-of-an-uploaded-dmn-file-fails-dmn-01002-unable-to-evaluate-expression-for-language-juel/2823) are more information about the problem.
Thanks a lot for your help!

**Comment by avan2s** [comment]
UPDATE: It seems to be, that there is an issue in the bindings:
org.camunda.bpm.engine.impl.juel.AstIdentifier:line77 -> 
method public Object eval(Bindings bindings, ELContext context) {
		ValueExpression expression = bindings.getVariable(index); // bindings have no variables. So expression contains null;

Maybe there is a bug in org.camunda.bpm.engine.impl.juel.TreeValueExpression in line 65?
this.bindings = tree.bind(functions, variables, converter); // Bindings are not set correctly

**Comment by rbraeunlich** [comment]
Hi avan2s,
this sounds like a general EL problem and not like something OSGi related.
So far I haven't tried to use DMN within OSGi. There are no test cases for that scenario, yet.
Cheers,
Ronny

**Comment by avan2s** [comment]
Hi Ronny,

thank you for your quick reply. In a non OSGI context i have no problems with evaluating a DMN file in version 7.4, 7.5 and 7.6. [Here](https://github.com/avan2s/camunda-engine-unittest-1) you see my working version without OSGi. However i found out in debugging mode, that in our project in an OSGI-context the list "resolvers" in class org.camunda.bpm.engine.impl.javax.el.CompositeELResolver in line 230 contains a org.camunda.bpm.extension.osgi.blueprint.BlueprintELResolver. Maybe there is an issue?

I would be really greatful if you or someone else can try to evaluate a DMN-file in an osgi-environment. My fear is, that it is not possible to evaluate a decision within OSGi. For our osgi-project (and i think for other OSGi-projects) it is important to have a working decision engine.

Many thanks in advance!

Cheers,
Andy

**Comment by rbraeunlich** [comment]
Hi Andy,

is your OSGi project running Blueprint?
For the BlueprintELResolver to be present, it has to be registered as a listener to perform the lookup of JavaDelegates. You can find the description [here](https://github.com/camunda/camunda-bpm-platform-osgi/tree/master/camunda-bpm-blueprint-wrapper#referencing-inside-processes).
Alternatively, the OSGiELResolver performs a lookup of exported services.

Cheers,
Ronny
