### ISSUE TITLE
Error Code-11001 - Problem with transaction Manager and throwing up exception to the client

### ISSUE THREAD

**Issue by avan2s** [camunda/camunda-bpm-platform-osgi#46]
Hello,

we have some problems, which randomly occur in the context of an transactionManager, which is used by the JTAConfiguration Factory. You can find a detailed description [here](https://forum.camunda.org/t/error-code-11001-problem-with-transaction-manager-and-throwing-up-exception-to-the-client/4007/1). I don't know if this is an osgi related or just a configuration issue on our side. So i would be really grateful, if you can look for it. I will also mention, that the service implementation, which is used in the delegate is injected from another bundle.

Cheers,
Andy

**Comment by rbraeunlich** [comment]
I close this issue because the discussion is going on in the forum thread and it's not related to OSGi
