### ISSUE TITLE
is there a way to get cockpit working with camunda-bpm-platform-osgi

### ISSUE THREAD

**Issue by elkhadirzyad** [camunda/camunda-bpm-platform-osgi#63]
Hello,

i'm try to make cockpit works in karaf container,  but i have "The process engine you are trying to access does not exist", is there a way to define or get the process engine ?

**Comment by rbraeunlich** [comment]
Hello @elkhadirzyad 
do you have any bundle in your Karaf that exposes/configures a process engine?

**Comment by elkhadirzyad** [comment]
I have an already existed process engine created by other person, how to use it in my camunda

**Comment by rbraeunlich** [comment]
Hey @elkhadirzyad 
there is no special cockpit-osgi adaption. Therefore, I cannot tell you anything exact. You'll most likely have to write some code to perform a service lookup and then pass the engine to cockpit.

**Comment by rbraeunlich** [comment]
See #64
