### ISSUE TITLE
Update repo name + product mentions

### ISSUE THREAD

**Issue by xomiamoore** [camunda/camunda-bpm-platform-osgi#78]
Hello! With the new product names, this repo name should be updated to something like "camunda-platform-7-osgi" to reduce confusion. Please let me know if I can help with this process!

**Comment by rbraeunlich** [comment]
Hi @xomiamoore,
I do not have the necessary permissions to rename this repository. Feel free to change the name though.

**Comment by xomiamoore** [comment]
Hey @rbraeunlich, I added you as a Maintainer which I think should give you permissions. I am happy to change the name myself, but will it break anything else in the repo? That's what I'm nervous about.

**Comment by rbraeunlich** [comment]
Hi @xomiamoore,
thank you for adding me. Changing the name shouldn't break anything. According to the GitHub documentation even the Git remote references should continue working.

**Comment by xomiamoore** [comment]
Okay, great. I went ahead and changed the repo name so I'll close this issue. 🤞🏻  that everything is fine :)
